cache: packages
sudo: required
warnings_are_errors: true

before_install: [
   "sudo add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ xenial main\" -y",
   "sudo apt-get update -q",
   "sudo apt-get install libfreetype6"
   ]

language: r
r:
- bioc-release

r_binary_packages:
- assertthat
- crayon
- dplyr
- FNN
- ggplot2
- glasso
- ggrepel
- Matrix
- plyr
- reshape2
- stringr
- tibble
- VGAM
- bh
- boot
- class
- cli
- cluster
- codetools
- colorspace
- crayon
- digest
- fansi
- foreign
- gdtools
- glue
- gtable
- kernsmooth
- labeling
- lattice
- lazyeval
- littler
- magrittr
- mass
- mgcv
- nlme
- nnet
- pillar
- pkgconfig 
- pkgkitten 
- plogr
- purrr
- r6
- rcolorbrewer
- rcpp
- rlang
- rpart
- scales
- spatial
- stringi
- survival
- svglite
- tidyselect
- tidyr
- utf8
- viridislite
- withr

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: sFOlT9BYAUZLqt+RDtLdbGbG411FU56IEALGIoPiHHhmCoWEbyaVJfhasRh5SZShhAjUvxiTMPkA05prjrQBHkzVozkPhNPUZSwezp5zaKpsQerBVHtc5jN5xaZinvqLK0TNKk1zq5pnBMwcRg54RVQe/petTsiuttxkmyJSAgztiterifMnhUefaJURNvd2AYvi57agUhu41j3xQnarnXdJR8YZtAaXDoYdC9kckJwrf6ZsBBWCe/P0kg1YZt/86SiCGidcjmNOqbAud7/tKJKzjFaU2R1v8ecyZiGSXWFVfbUt/27Ur+8IzJiV0Qn08Ru6TwJSqS/fbc+2vWYo6MWKkfZtK4HhoWsYXyk7jnOP2DTynFMidthGR+qxLxpBuvQbGtPRgcm1DVjDl2Z3MqXz1RbAmnbCDOWNF21go1yIAKCxgHd2a/2TtLsbJsZwyGwSmrxhoF+CH4kJ2mgKarwyKGTLs5L6/eQfXR31hQc0h0eKMLlBkweTkxOguCrO30cuQvZ+bm/pFmR9doyZLP23/cYbnu0AsxgOa/SJ57MjDG2gKYmuzlBXPhNl30M9OIc0P1WRNHmk6aW4wZn6VKYBOAq1gGMM2k8g5x/OPM01R2c5ZJ7Fwizh4kaocXydfxGoJOSO1JPE+r/G339GgTuXyEekgA0dcF0j3recLyQ=
