cache: packages
sudo: required
warnings_are_errors: true

before_install: 
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main" -y
  - sudo apt-get update -q
  - sudo apt-get install libfreetype6
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install -y gdal-bin
  - sudo apt-get install -y libgdal1-dev

language: r
r:
- bioc-release

r_github_packages:
- cole-trapnell-lab/monocle3

r_binary_packages:
- crayon
- Matrix
- plyr
- reshape2
- stringr
- VGAM
- boot
- class
- cluster
- codetools
- colorspace
- crayon
- digest
- foreign
- gtable
- kernsmooth
- labeling
- lattice
- littler
- magrittr
- mass
- mgcv
- nlme
- nnet
- pkgkitten 
- rcolorbrewer
- rcpp
- rpart
- scales
- spatial
- stringi
- survival

script: 
  - |
    travis_wait 20 R CMD build --no-build-vignettes .
    travis_wait 20 R CMD check --no-build-vignettes cicero*tar.gz
    
after_success:
- Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: sFOlT9BYAUZLqt+RDtLdbGbG411FU56IEALGIoPiHHhmCoWEbyaVJfhasRh5SZShhAjUvxiTMPkA05prjrQBHkzVozkPhNPUZSwezp5zaKpsQerBVHtc5jN5xaZinvqLK0TNKk1zq5pnBMwcRg54RVQe/petTsiuttxkmyJSAgztiterifMnhUefaJURNvd2AYvi57agUhu41j3xQnarnXdJR8YZtAaXDoYdC9kckJwrf6ZsBBWCe/P0kg1YZt/86SiCGidcjmNOqbAud7/tKJKzjFaU2R1v8ecyZiGSXWFVfbUt/27Ur+8IzJiV0Qn08Ru6TwJSqS/fbc+2vWYo6MWKkfZtK4HhoWsYXyk7jnOP2DTynFMidthGR+qxLxpBuvQbGtPRgcm1DVjDl2Z3MqXz1RbAmnbCDOWNF21go1yIAKCxgHd2a/2TtLsbJsZwyGwSmrxhoF+CH4kJ2mgKarwyKGTLs5L6/eQfXR31hQc0h0eKMLlBkweTkxOguCrO30cuQvZ+bm/pFmR9doyZLP23/cYbnu0AsxgOa/SJ57MjDG2gKYmuzlBXPhNl30M9OIc0P1WRNHmk6aW4wZn6VKYBOAq1gGMM2k8g5x/OPM01R2c5ZJ7Fwizh4kaocXydfxGoJOSO1JPE+r/G339GgTuXyEekgA0dcF0j3recLyQ=
